import React, { useState } from 'react';
import { 
  Box, 
  Plus, 
  Search, 
  Filter, 
  MoreVertical, 
  Edit2, 
  Trash2, 
  ExternalLink,
  ChevronRight,
  Package,
  TrendingUp,
  AlertTriangle,
  ArrowUpDown,
  Sparkles,
  DollarSign,
  Layers,
  FileText,
  Save,
  Upload,
  X,
  MapPin,
  Image as ImageIcon,
  Barcode,
  CheckCircle2
} from 'lucide-react';
import JsBarcode from 'jsbarcode';
import { Product } from '../../types/store';
import { CATEGORIES } from '../../data/products';
import { saveRealtimeProduct, deleteRealtimeProduct, addRealtimeNotification } from '../../services/supabaseService';
import { useLanguageCurrency } from '../../context/LanguageCurrencyContext';
import { SUPPORTED_CURRENCIES } from '../../data/currencies';
import { FastActionLoader } from '../FastLoadingScreen';

interface AdminProductsProps {
  products: Product[];
  setProducts: React.Dispatch<React.SetStateAction<Product[]>>;
  categories: { id: string; label: string }[];
  brands: { name: string; origin: string }[];
  initialSearchQuery?: string;
  onNewProductAdded?: (product: Product) => void;
}

export const AdminProducts: React.FC<AdminProductsProps> = ({ 
  products, 
  setProducts, 
  categories, 
  brands,
  initialSearchQuery,
  onNewProductAdded
}) => {
  const { currency, formatPrice } = useLanguageCurrency();
  const [searchQuery, setSearchQuery] = useState(initialSearchQuery || '');
  const [categoryFilter, setCategoryFilter] = useState('all');

  React.useEffect(() => {
    if (initialSearchQuery !== undefined) {
      setSearchQuery(initialSearchQuery);
    }
  }, [initialSearchQuery]);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [priceCurrency, setPriceCurrency] = useState<string>(currency.code || 'XOF');
  const [salePriceInput, setSalePriceInput] = useState<string>('');
  const [origPriceInput, setOrigPriceInput] = useState<string>('');
  const [isSaving, setIsSaving] = useState(false);

  const [formData, setFormData] = useState<Partial<Product>>({
    name: '',
    subtitle: '',
    tagline: '',
    price: 0,
    originalPrice: 0,
    category: 'essentials',
    categoryLabel: 'Essentials',
    brand: '',
    brandOrigin: '',
    tag: '',
    description: '',
    materials: '',
    care: '',
    madeIn: '',
    primaryImage: '',
    featured: false,
    isNewArrival: false,
    isHotDeal: false,
    sku: '',
    barcode: '',
    stockLevel: 0,
  });

  const [error, setError] = useState<string | null>(null);
  const [deleteConfirmationId, setDeleteConfirmationId] = useState<string | null>(null);

  // Auto-generate SKU and Barcode
  const generateIdentifiers = () => {
    const newSku = `SKU-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
    const newBarcode = Math.floor(Math.random() * 1000000000000).toString().padStart(12, '0');
    setFormData(prev => ({
      ...prev,
      sku: newSku,
      barcode: newBarcode
    }));
  };

  const handleAutoGenerateDescription = async () => {
    if (!formData.name || !formData.materials) {
      setError('Please provide product name and materials first.');
      return;
    }
    setError(null);
    try {
      const response = await fetch('/api/generate-description', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: formData.name, materials: formData.materials, category: formData.categoryLabel }),
      });
      const data = await response.json();
      if (data.description) {
        setFormData(prev => ({ ...prev, description: data.description }));
      } else {
        setError('Failed to generate description.');
      }
    } catch (e) {
      setError('Error connecting to description service.');
    }
  };

  const handleOpenModal = (product?: Product) => {
    const activeCode = currency.code || 'XOF';
    setPriceCurrency(activeCode);
    const rate = SUPPORTED_CURRENCIES[activeCode]?.rate || 1;
    const decimals = SUPPORTED_CURRENCIES[activeCode]?.decimals || 0;

    if (product) {
      setEditingProduct(product);
      const convertedSale = (product.price * rate).toFixed(decimals);
      const convertedOrig = product.originalPrice ? (product.originalPrice * rate).toFixed(decimals) : '';
      setSalePriceInput(convertedSale);
      setOrigPriceInput(convertedOrig);

      setFormData({
        ...product,
        images: product.images || []
      });
    } else {
      setEditingProduct(null);
      setSalePriceInput('');
      setOrigPriceInput('');
      setFormData({
        name: '',
        subtitle: 'Premium Acquisition',
        tagline: 'Excellence in Craftsmanship',
        price: 0,
        originalPrice: 0,
        category: 'essentials',
        categoryLabel: 'Essentials',
        brand: 'GLADYNS',
        brandOrigin: 'Europe',
        tag: 'New Arrival',
        description: '',
        materials: 'Premium Materials',
        care: 'Professional dry clean only',
        madeIn: 'Portugal',
        primaryImage: '',
        featured: false,
        isNewArrival: true,
        isHotDeal: false,
        images: [],
        colors: [{ id: 'col-1', name: 'Standard', colorHex: '#000000', inStock: true }],
        sizes: [
          { name: 'S', inStock: true },
          { name: 'M', inStock: true },
          { name: 'L', inStock: true }
        ],
        details: [],
        reviewCount: 0,
        rating: 5,
        reviews: [],
        sku: `SKU-${Math.random().toString(36).substring(2, 8).toUpperCase()}`,
        barcode: Math.floor(Math.random() * 1000000000000).toString().padStart(12, '0'),
        stockLevel: 0,
      });
    }
    setIsModalOpen(true);
  };

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = error => reject(error);
    });
  };

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;

    const currentImages = formData.images || [];
    const remainingSlots = 4 - currentImages.length;
    
    if (remainingSlots <= 0) {
      setError('Maximum 4 images allowed per product.');
      return;
    }

    const filesToUpload = Array.from(files).slice(0, remainingSlots);
    
    try {
      const base64Images = await Promise.all(filesToUpload.map(file => fileToBase64(file)));
      const newImageObjects = base64Images.map(base64 => ({
        url: base64,
        alt: formData.name || 'Product Image'
      }));

      const updatedImages = [...currentImages, ...newImageObjects];
      
      setFormData(prev => ({
        ...prev,
        images: updatedImages,
        primaryImage: prev.primaryImage || updatedImages[0]?.url
      }));
    } catch (err) {
      console.error('Image upload failed:', err);
    }
  };

  const removeImage = (index: number) => {
    const updatedImages = (formData.images || []).filter((_, i) => i !== index);
    setFormData(prev => ({
      ...prev,
      images: updatedImages,
      primaryImage: prev.primaryImage === prev.images?.[index].url 
        ? updatedImages[0]?.url || '' 
        : prev.primaryImage
    }));
  };

  const setPrimaryImage = (url: string) => {
    setFormData(prev => ({ ...prev, primaryImage: url }));
  };

  const handleSaveProduct = () => {
    const rawSale = parseFloat(salePriceInput);
    if (!formData.name || isNaN(rawSale) || rawSale <= 0) {
      setError('Please provide at least a product name and a valid sale price.');
      return;
    }

    setIsSaving(true);

    // Convert from the chosen currency to base USD storage value
    const curRate = SUPPORTED_CURRENCIES[priceCurrency]?.rate || 1;
    const basePrice = rawSale / curRate;
    const rawOrig = parseFloat(origPriceInput);
    const baseOrigPrice = !isNaN(rawOrig) && rawOrig > 0 ? rawOrig / curRate : undefined;
    
    const finalFormData: Product = {
      ...(formData as Product),
      price: basePrice,
      originalPrice: baseOrigPrice,
    };
    
    setTimeout(() => {
      if (editingProduct) {
        const updated = { ...editingProduct, ...finalFormData };
        setProducts(prev => prev.map(p => p.id === editingProduct.id ? updated : p));
        saveRealtimeProduct(updated);
      } else {
        const product: Product = {
          ...finalFormData,
          id: `prod-${Date.now()}`,
          slug: (formData.name || '')?.toLowerCase().replace(/\s+/g, '-'),
        };
        setProducts(prev => [product, ...prev]);
        saveRealtimeProduct(product);
        addRealtimeNotification({
          id: `notif-new-product-${product.id}-${Date.now()}`,
          title: `✨ New Arrival: ${product.name}`,
          message: `Discover our newest addition: "${product.name}" is now available in store for $${product.price.toFixed(2)}.`,
          timestamp: Date.now(),
          read: false,
          type: 'product',
          linkTarget: product.id,
        });
        if (onNewProductAdded) {
          onNewProductAdded(product);
        }
      }
      setIsSaving(false);
      setIsModalOpen(false);
    }, 300);
  };

  const handleDeleteProduct = () => {
    if (deleteConfirmationId) {
      setProducts(prev => prev.filter(p => p.id !== deleteConfirmationId));
      deleteRealtimeProduct(deleteConfirmationId);
      setDeleteConfirmationId(null);
    }
  };

  const filteredProducts = products.filter(product => {
    const q = searchQuery?.toLowerCase().trim();
    if (!q) return categoryFilter === 'all' || product.category === categoryFilter;

    const matchesSearch = 
      product.name?.toLowerCase().includes(q) ||
      product.id?.toLowerCase().includes(q) ||
      (product.sku && product.sku?.toLowerCase().includes(q)) ||
      product.categoryLabel?.toLowerCase().includes(q) ||
      (product.brand && product.brand?.toLowerCase().includes(q));
    
    const matchesCategory = categoryFilter === 'all' || product.category === categoryFilter;
    
    return matchesSearch && matchesCategory;
  });

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-display font-bold text-zinc-900">Product Management</h2>
            <span className="px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-zinc-100 text-zinc-800">
              Catalog & Drops
            </span>
          </div>
          <p className="text-sm text-zinc-500 mt-1">Create, edit, curate descriptions, specifications, photos, and live storefront catalog pieces.</p>
        </div>
        <div className="flex items-center gap-3">
          <button 
            onClick={() => handleOpenModal()}
            className="flex items-center gap-2 px-4 py-2 bg-zinc-900 text-white rounded-xl text-sm font-semibold hover:bg-zinc-800 transition-all shadow-lg shadow-zinc-200 cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>Add New Arrival</span>
          </button>
        </div>
      </div>

      {/* Advanced Product Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-zinc-950/40 backdrop-blur-sm">
          <div className="bg-white rounded-3xl w-full max-w-4xl max-h-[90vh] overflow-y-auto shadow-2xl border border-zinc-200">
            <div className="p-6 sm:p-8 border-b border-zinc-100 flex items-center justify-between sticky top-0 bg-white z-10">
              <div>
                <h3 className="text-xl font-bold text-zinc-900">{editingProduct ? 'Edit Catalogue Piece' : 'Catalogue New Arrival'}</h3>
                <p className="text-xs text-zinc-500 mt-1">Configure advanced product parameters and assets.</p>
              </div>
              <button onClick={() => setIsModalOpen(false)} className="p-2 hover:bg-zinc-100 rounded-full transition-colors">
                <Plus className="w-6 h-6 rotate-45 text-zinc-400" />
              </button>
            </div>
            
            <div className="p-6 sm:p-8 space-y-8">
              {error && (
                <div className="p-4 bg-rose-50 border border-rose-100 text-rose-600 text-xs font-bold rounded-2xl flex items-center gap-3 animate-in fade-in slide-in-from-top-2">
                  <AlertTriangle className="w-4 h-4" />
                  {error}
                </div>
              )}
              {/* Basic Information Section */}
              <div className="space-y-6">
                <div className="flex items-center gap-2 text-zinc-900">
                  <Box className="w-4 h-4 text-blue-600" />
                  <h4 className="text-xs font-black uppercase tracking-widest">Basic Information</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Piece Name</label>
                    <input 
                      type="text" 
                      placeholder="e.g. Silk Chore Coat"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all font-bold"
                      value={formData.name}
                      onChange={(e) => setFormData({...formData, name: e.target.value})}
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Subtitle / Collection</label>
                    <input 
                      type="text" 
                      placeholder="e.g. Premium Acquisition"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all"
                      value={formData.subtitle}
                      onChange={(e) => setFormData({...formData, subtitle: e.target.value})}
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Tagline</label>
                    <input 
                      type="text" 
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all"
                      value={formData.tagline}
                      onChange={(e) => setFormData({...formData, tagline: e.target.value})}
                    />
                  </div>
                </div>
              </div>

              {/* Commercials Section */}
              <div className="space-y-6 pt-6 border-t border-zinc-100">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-zinc-900">
                    <DollarSign className="w-4 h-4 text-emerald-600" />
                    <h4 className="text-xs font-black uppercase tracking-widest">Financials & Pricing</h4>
                  </div>
                  
                  {/* Currency Picker */}
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-black uppercase tracking-wider text-zinc-400">Input Currency:</span>
                    <select
                      value={priceCurrency}
                      onChange={(e) => {
                        const newCode = e.target.value;
                        const oldRate = SUPPORTED_CURRENCIES[priceCurrency]?.rate || 1;
                        const newRate = SUPPORTED_CURRENCIES[newCode]?.rate || 1;
                        const decimals = SUPPORTED_CURRENCIES[newCode]?.decimals || 0;
                        setPriceCurrency(newCode);

                        // Convert current input values if entered
                        if (salePriceInput && !isNaN(parseFloat(salePriceInput))) {
                          const base = parseFloat(salePriceInput) / oldRate;
                          setSalePriceInput((base * newRate).toFixed(decimals));
                        }
                        if (origPriceInput && !isNaN(parseFloat(origPriceInput))) {
                          const base = parseFloat(origPriceInput) / oldRate;
                          setOrigPriceInput((base * newRate).toFixed(decimals));
                        }
                      }}
                      className="px-2.5 py-1 bg-zinc-100 border border-zinc-200 rounded-lg text-xs font-bold text-zinc-900 focus:outline-none focus:border-zinc-900 cursor-pointer"
                    >
                      <option value="XOF">🇨🇮 Franc CFA (XOF)</option>
                      <option value="USD">🇺🇸 US Dollar (USD $)</option>
                      <option value="EUR">🇪🇺 Euro (EUR €)</option>
                      <option value="GBP">🇬🇧 British Pound (GBP £)</option>
                      <option value="CAD">🇨🇦 Canadian Dollar (CAD $)</option>
                      <option value="NGN">🇳🇬 Nigerian Naira (NGN ₦)</option>
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest flex items-center justify-between">
                      <span className="flex items-center gap-1.5">
                        <TrendingUp className="w-3.5 h-3.5 text-emerald-600" />
                        Sale Price ({SUPPORTED_CURRENCIES[priceCurrency]?.symbol || priceCurrency})
                      </span>
                      <span className="text-[10px] text-zinc-400 font-mono">
                        {priceCurrency}
                      </span>
                    </label>
                    <div className="relative">
                      <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-xs font-bold text-zinc-400">
                        {SUPPORTED_CURRENCIES[priceCurrency]?.symbol}
                      </span>
                      <input 
                        type="number" 
                        step="any"
                        placeholder="e.g. 10000"
                        className="w-full pl-9 pr-4 py-3 bg-zinc-50 border border-zinc-200 rounded-xl text-sm focus:bg-white focus:ring-2 focus:ring-emerald-500/10 transition-all font-bold text-emerald-600"
                        value={salePriceInput}
                        onChange={(e) => setSalePriceInput(e.target.value)}
                      />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-500 uppercase tracking-widest flex items-center justify-between">
                      <span className="flex items-center gap-1.5">
                        <Box className="w-3.5 h-3.5 text-zinc-400" />
                        Original Retail Price (Optional for Discount Strikethrough)
                      </span>
                      <span className="text-[10px] text-zinc-400 font-mono">
                        {priceCurrency}
                      </span>
                    </label>
                    <div className="relative">
                      <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-xs font-bold text-zinc-400">
                        {SUPPORTED_CURRENCIES[priceCurrency]?.symbol}
                      </span>
                      <input 
                        type="number" 
                        step="any"
                        placeholder="0.00"
                        className="w-full pl-9 pr-4 py-3 bg-zinc-50 border border-zinc-200 rounded-xl text-sm focus:bg-white focus:ring-2 focus:ring-zinc-950/10 transition-all font-bold text-zinc-500"
                        value={origPriceInput}
                        onChange={(e) => setOrigPriceInput(e.target.value)}
                      />
                    </div>
                  </div>
                </div>

                {/* Live Currency Conversion Preview Card */}
                {salePriceInput && !isNaN(parseFloat(salePriceInput)) && parseFloat(salePriceInput) > 0 && (
                  <div className="bg-emerald-50/60 border border-emerald-100/80 rounded-2xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                    <div className="flex items-center gap-2 text-emerald-900">
                      <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                      <div>
                        <p className="text-xs font-bold">
                          Storefront Live Conversion Preview
                        </p>
                        <p className="text-[11px] text-emerald-700">
                          Customers around the world will see this price calculated accurately in their local currency:
                        </p>
                      </div>
                    </div>

                    {(() => {
                      const curRate = SUPPORTED_CURRENCIES[priceCurrency]?.rate || 1;
                      const baseUSD = parseFloat(salePriceInput) / curRate;
                      const cfaVal = Math.round(baseUSD * 605).toLocaleString();
                      const usdVal = baseUSD.toFixed(2);
                      const eurVal = (baseUSD * 0.92).toFixed(2);

                      return (
                        <div className="flex items-center gap-2 flex-wrap shrink-0">
                          <span className="px-2.5 py-1 bg-white border border-emerald-200 rounded-lg text-xs font-mono font-bold text-zinc-900">
                            🇨🇮 {cfaVal} CFA
                          </span>
                          <span className="px-2.5 py-1 bg-white border border-emerald-200 rounded-lg text-xs font-mono font-bold text-zinc-900">
                            🇺🇸 ${usdVal}
                          </span>
                          <span className="px-2.5 py-1 bg-white border border-emerald-200 rounded-lg text-xs font-mono font-bold text-zinc-900">
                            🇪🇺 {eurVal} €
                          </span>
                        </div>
                      );
                    })()}
                  </div>
                )}
              </div>

              {/* Taxonomy & Branding Section */}
              <div className="space-y-6 pt-6 border-t border-zinc-100">
                <div className="flex items-center gap-2 text-zinc-900">
                  <Layers className="w-4 h-4 text-blue-600" />
                  <h4 className="text-xs font-black uppercase tracking-widest">Classification & Branding</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Dedicated Category</label>
                    <select 
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all font-bold"
                      value={formData.category}
                      onChange={(e) => setFormData({...formData, category: e.target.value, categoryLabel: e.target.options[e.target.selectedIndex].text})}
                    >
                      <option value="">Select Category / Department</option>
                      {categories.filter(c => c.id !== 'all').map(cat => (
                          <option key={cat.id} value={cat.id}>{cat.label}</option>
                        ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">House / Brand Selection</label>
                    <select 
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all font-bold"
                      value={formData.brand}
                      onChange={(e) => {
                        const selectedBrand = brands.find(b => b.name === e.target.value);
                        setFormData({...formData, brand: e.target.value, brandOrigin: selectedBrand?.origin || formData.brandOrigin});
                      }}
                    >
                      <option value="">Select Brand</option>
                      {brands.map(b => (
                        <option key={b.name} value={b.name}>{b.name}</option>
                      ))}
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest flex items-center gap-2">
                      <MapPin className="w-3 h-3" /> Brand Origin / Provenance
                    </label>
                    <input 
                      type="text" 
                      placeholder="e.g. Porto, Portugal"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all"
                      value={formData.brandOrigin}
                      onChange={(e) => setFormData({...formData, brandOrigin: e.target.value})}
                    />
                  </div>
                </div>
              </div>

              {/* Assets Section */}
              <div className="space-y-6 pt-6 border-t border-zinc-100">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-zinc-900">
                    <ImageIcon className="w-4 h-4 text-blue-400" />
                    <h4 className="text-xs font-black uppercase tracking-widest">Digital Assets (Max 4 Images)</h4>
                  </div>
                  <label className="flex items-center gap-2 px-3 py-1.5 bg-blue-50 text-blue-600 rounded-lg text-[10px] font-black uppercase cursor-pointer hover:bg-blue-100 transition-all">
                    <Upload className="w-3.5 h-3.5" />
                    <span>Upload Images</span>
                    <input 
                      type="file" 
                      multiple 
                      accept="image/*" 
                      className="hidden" 
                      onChange={handleImageUpload}
                      disabled={(formData.images || []).length >= 4}
                    />
                  </label>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                  {(formData.images || []).map((img, idx) => (
                    <div key={idx} className="relative aspect-square rounded-2xl overflow-hidden border border-zinc-200 group bg-zinc-50">
                      <img src={img.url} alt={`Preview ${idx}`} className="w-full h-full object-cover" />
                      <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col items-center justify-center gap-2">
                        <button 
                          onClick={() => removeImage(idx)}
                          className="p-1.5 bg-rose-600 text-white rounded-full hover:bg-rose-700 transition-all"
                        >
                          <X className="w-3.5 h-3.5" />
                        </button>
                        <button 
                          onClick={() => setPrimaryImage(img.url)}
                          className={`px-2 py-1 rounded text-[8px] font-black uppercase transition-all ${
                            formData.primaryImage === img.url 
                              ? 'bg-emerald-500 text-white' 
                              : 'bg-white text-zinc-900 hover:bg-zinc-100'
                          }`}
                        >
                          {formData.primaryImage === img.url ? 'Primary' : 'Set Primary'}
                        </button>
                      </div>
                      {formData.primaryImage === img.url && (
                        <div className="absolute top-2 left-2 px-1.5 py-0.5 bg-emerald-500 text-white text-[8px] font-black uppercase rounded shadow-sm">
                          Primary
                        </div>
                      )}
                    </div>
                  ))}
                  
                  {(formData.images || []).length < 4 && (
                    <label className="aspect-square rounded-2xl border-2 border-dashed border-zinc-200 flex flex-col items-center justify-center gap-2 text-zinc-400 hover:border-zinc-300 hover:text-zinc-500 transition-all cursor-pointer bg-zinc-50/30">
                      <Plus className="w-6 h-6" />
                      <span className="text-[10px] font-bold uppercase tracking-widest">Add Image</span>
                      <input 
                        type="file" 
                        accept="image/*" 
                        className="hidden" 
                        onChange={handleImageUpload}
                      />
                    </label>
                  )}
                </div>

                <div className="space-y-2">
                  <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Or Provide Primary Image URL (Fallback)</label>
                  <input 
                    type="text" 
                    className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all"
                    value={formData.primaryImage}
                    onChange={(e) => setFormData({...formData, primaryImage: e.target.value})}
                  />
                </div>
              </div>

              {/* Content Section */}
              <div className="space-y-6 pt-6 border-t border-zinc-100">
                <div className="flex items-center gap-2 text-zinc-900">
                  <FileText className="w-4 h-4 text-amber-600" />
                  <h4 className="text-xs font-black uppercase tracking-widest">Editorial Content</h4>
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest flex items-center justify-between">
                    Artisanal Narrative
                    <button onClick={handleAutoGenerateDescription} className="text-blue-600 hover:underline">Auto-Generate</button>
                  </label>
                  <textarea 
                    rows={4}
                    placeholder="Describe the craftsmanship, materials, and inspiration..."
                    className="w-full p-4 bg-zinc-50 border border-zinc-100 rounded-2xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all resize-none leading-relaxed"
                    value={formData.description}
                    onChange={(e) => setFormData({...formData, description: e.target.value})}
                  />
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Materials</label>
                    <input 
                      type="text" 
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all"
                      value={formData.materials}
                      onChange={(e) => setFormData({...formData, materials: e.target.value})}
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Care Instructions</label>
                    <input 
                      type="text" 
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all"
                      value={formData.care}
                      onChange={(e) => setFormData({...formData, care: e.target.value})}
                    />
                  </div>
                </div>
              </div>

              {/* Inventory Tracking Section */}
              <div className="space-y-6 pt-6 border-t border-zinc-100">
                <div className="flex items-center gap-2 text-zinc-900">
                  <Package className="w-4 h-4 text-blue-500" />
                  <h4 className="text-xs font-black uppercase tracking-widest">Inventory & Tracking</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest flex items-center justify-between">
                      Product SKU
                      <button onClick={generateIdentifiers} className="text-blue-600 hover:underline">Auto-Gen</button>
                    </label>
                    <input 
                      type="text" 
                      placeholder="e.g. GL-EXT-001"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all font-mono uppercase"
                      value={formData.sku}
                      onChange={(e) => setFormData({...formData, sku: e.target.value.toUpperCase()})}
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Barcode</label>
                    <div className="flex gap-2">
                      <input 
                        type="text" 
                        placeholder="e.g. 123456789012"
                        className="flex-1 px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all font-mono"
                        value={formData.barcode}
                        onChange={(e) => setFormData({...formData, barcode: e.target.value})}
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Current Stock Level</label>
                    <input 
                      type="number" 
                      placeholder="0"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all font-bold"
                      value={formData.stockLevel}
                      onChange={(e) => setFormData({...formData, stockLevel: parseInt(e.target.value) || 0})}
                    />
                  </div>
                </div>
              </div>

              {/* Promotions & Visibility Section */}
              <div className="space-y-6 pt-6 border-t border-zinc-100">
                <div className="flex items-center gap-2 text-zinc-900">
                  <Sparkles className="w-4 h-4 text-amber-500" />
                  <h4 className="text-xs font-black uppercase tracking-widest">Promotions & Visibility</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Promo Tag / Label</label>
                    <input 
                      type="text" 
                      placeholder="e.g. Limited Edition, Hot Deal"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all"
                      value={formData.tag}
                      onChange={(e) => setFormData({...formData, tag: e.target.value})}
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Discount Highlight (%)</label>
                    <input 
                      type="number" 
                      placeholder="0"
                      className="w-full px-4 py-3 bg-zinc-50 border border-zinc-100 rounded-xl text-sm focus:ring-2 focus:ring-zinc-950/10 transition-all"
                      value={formData.discountPercentage}
                      onChange={(e) => setFormData({...formData, discountPercentage: parseFloat(e.target.value)})}
                    />
                  </div>
                </div>

                <div className="flex flex-wrap gap-6 pt-2">
                  <label className="flex items-center gap-3 cursor-pointer group">
                    <input 
                      type="checkbox" 
                      className="w-5 h-5 rounded-md border-zinc-300 text-zinc-950 focus:ring-zinc-950"
                      checked={formData.featured}
                      onChange={(e) => setFormData({...formData, featured: e.target.checked})}
                    />
                    <span className="text-xs font-bold text-zinc-700 group-hover:text-zinc-950 transition-colors">Featured Piece</span>
                  </label>
                  <label className="flex items-center gap-3 cursor-pointer group">
                    <input 
                      type="checkbox" 
                      className="w-5 h-5 rounded-md border-zinc-300 text-blue-600 focus:ring-blue-500"
                      checked={formData.isNewArrival}
                      onChange={(e) => setFormData({...formData, isNewArrival: e.target.checked})}
                    />
                    <span className="text-xs font-bold text-zinc-700 group-hover:text-zinc-950 transition-colors">New Arrival</span>
                  </label>
                  <label className="flex items-center gap-3 cursor-pointer group">
                    <input 
                      type="checkbox" 
                      className="w-5 h-5 rounded-md border-zinc-300 text-rose-600 focus:ring-rose-500"
                      checked={formData.isHotDeal}
                      onChange={(e) => setFormData({...formData, isHotDeal: e.target.checked})}
                    />
                    <span className="text-xs font-bold text-zinc-700 group-hover:text-zinc-950 transition-colors">Hot Deal</span>
                  </label>
                </div>
              </div>

              <div className="pt-8 border-t border-zinc-100">
                <button 
                  onClick={handleSaveProduct}
                  className="w-full py-4 bg-zinc-900 text-white rounded-2xl font-bold hover:bg-zinc-800 transition-all shadow-xl shadow-zinc-200 flex items-center justify-center gap-2"
                >
                  <Save className="w-5 h-5" />
                  <span>{editingProduct ? 'Update Catalogue Piece' : 'Catalogue Piece'}</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Stats Quick View */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white p-4 rounded-2xl border border-zinc-200 shadow-sm">
          <p className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Total SKU Count</p>
          <div className="flex items-center justify-between mt-1">
            <h4 className="text-xl font-display font-bold text-zinc-900">{products.length}</h4>
            <Box className="w-5 h-5 text-zinc-300" />
          </div>
        </div>
        <div className="bg-white p-4 rounded-2xl border border-zinc-200 shadow-sm">
          <p className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Featured Active</p>
          <div className="flex items-center justify-between mt-1">
            <h4 className="text-xl font-display font-bold text-zinc-900">{products.filter(p => p.featured).length}</h4>
            <Sparkles className="w-5 h-5 text-amber-500" />
          </div>
        </div>
        <div className="bg-white p-4 rounded-2xl border border-zinc-200 shadow-sm">
          <p className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">Hot Deals</p>
          <div className="flex items-center justify-between mt-1">
            <h4 className="text-xl font-display font-bold text-zinc-900">{products.filter(p => p.isHotDeal).length}</h4>
            <AlertTriangle className="w-5 h-5 text-rose-500" />
          </div>
        </div>
        <div className="bg-white p-4 rounded-2xl border border-zinc-200 shadow-sm">
          <p className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">New Arrivals</p>
          <div className="flex items-center justify-between mt-1">
            <h4 className="text-xl font-display font-bold text-zinc-900">{products.filter(p => p.isNewArrival).length}</h4>
            <TrendingUp className="w-5 h-5 text-emerald-500" />
          </div>
        </div>
      </div>

      {/* Filters & Search */}
      <div className="bg-white p-4 rounded-2xl border border-zinc-200 shadow-sm flex flex-col md:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 w-4 h-4 text-zinc-400" />
          <input
            type="text"
            placeholder="Search inventory by name, category, SKU, brand..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2 bg-zinc-50 border-none rounded-xl text-sm focus:ring-1 focus:ring-zinc-900"
          />
        </div>
        <div className="flex items-center gap-2">
          <Filter className="w-4 h-4 text-zinc-400" />
          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            className="bg-zinc-50 border-none rounded-xl text-sm px-4 py-2 focus:ring-1 focus:ring-zinc-900 font-semibold text-zinc-700"
          >
            <option value="all">All Categories</option>
            {categories.map(cat => (
              <option key={cat.id} value={cat.id}>{cat.label}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Products Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {filteredProducts.map((product) => (
          <div key={product.id} className="bg-white rounded-2xl border border-zinc-200 shadow-sm overflow-hidden group hover:border-zinc-300 transition-all">
            <div className="aspect-[4/5] bg-zinc-100 relative overflow-hidden">
              <img 
                src={product.primaryImage} 
                alt={product.name}
                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
              />
              <div className="absolute top-3 left-3 flex flex-col gap-2">
                {product.featured && (
                  <span className="bg-zinc-900 text-white text-[8px] font-black uppercase px-2 py-1 rounded-full">Featured</span>
                )}
                {product.isNewArrival && (
                  <span className="bg-blue-600 text-white text-[8px] font-black uppercase px-2 py-1 rounded-full">New</span>
                )}
                {product.isHotDeal && (
                  <span className="bg-rose-600 text-white text-[8px] font-black uppercase px-2 py-1 rounded-full">Hot Deal</span>
                )}
              </div>
              <div className="absolute top-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity">
                <div className="bg-white/90 backdrop-blur-sm rounded-xl p-1 flex flex-col gap-1 shadow-lg">
                  <button 
                    onClick={() => handleOpenModal(product)}
                    className="p-2 text-zinc-600 hover:text-zinc-900 transition-colors"
                  >
                    <Edit2 className="w-4 h-4" />
                  </button>
                  <button className="p-2 text-zinc-600 hover:text-zinc-900 transition-colors border-t border-zinc-200/50">
                    <ExternalLink className="w-4 h-4" />
                  </button>
                  <button 
                    onClick={() => setDeleteConfirmationId(product.id)}
                    className="p-2 text-rose-600 hover:text-rose-700 transition-colors border-t border-zinc-200/50"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            </div>
            <div className="p-4 space-y-3">
              <div>
                <div className="flex items-center justify-between mb-1">
                  <p className="text-[10px] font-black text-blue-600 uppercase tracking-widest">{product.categoryLabel}</p>
                  <p className="text-[10px] font-bold text-zinc-400">{product.brand}</p>
                </div>
                <h4 className="text-sm font-bold text-zinc-900 line-clamp-1">{product.name}</h4>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-bold text-zinc-900 font-mono">{formatPrice(product.price)}</span>
                  {product.originalPrice && product.originalPrice > product.price && (
                    <span className="text-[10px] text-zinc-400 line-through font-mono">{formatPrice(product.originalPrice)}</span>
                  )}
                </div>
                <div className="flex items-center gap-1.5">
                  <span className={`w-2 h-2 rounded-full ${product.sizes.some(s => s.inStock) ? 'bg-emerald-500' : 'bg-rose-500'}`}></span>
                  <span className="text-[10px] font-semibold text-zinc-500">
                    In Stock
                  </span>
                </div>
              </div>
              <div className="pt-3 border-t border-zinc-100 flex items-center justify-between">
                <button 
                  onClick={() => handleOpenModal(product)}
                  className="text-[10px] font-black text-zinc-400 uppercase tracking-widest hover:text-zinc-900 transition-colors"
                >
                  Manage Product
                </button>
                <div className="flex -space-x-1">
                  {product.colors.slice(0, 3).map((color, i) => (
                    <div 
                      key={i} 
                      className="w-3.5 h-3.5 rounded-full border border-white shadow-sm"
                      style={{ backgroundColor: color.colorHex }}
                    />
                  ))}
                  {product.colors.length > 3 && (
                    <div className="w-3.5 h-3.5 rounded-full bg-zinc-100 border border-white flex items-center justify-center text-[8px] font-bold text-zinc-500">
                      +{product.colors.length - 3}
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        ))}

        {/* Add New Placeholder */}
        <button 
          onClick={() => handleOpenModal()}
          className="aspect-[4/5] sm:aspect-auto rounded-2xl border-2 border-dashed border-zinc-200 flex flex-col items-center justify-center gap-4 text-zinc-400 hover:border-zinc-300 hover:text-zinc-500 transition-all group bg-zinc-50/30"
        >
          <div className="w-12 h-12 rounded-full bg-zinc-100 flex items-center justify-center group-hover:scale-110 transition-transform">
            <Plus className="w-6 h-6" />
          </div>
          <span className="text-xs font-bold uppercase tracking-widest">Add Piece</span>
        </button>
      </div>

      {/* Delete Confirmation Modal */}
      {deleteConfirmationId && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-zinc-950/40 backdrop-blur-sm">
          <div className="bg-white rounded-3xl w-full max-w-sm p-8 shadow-2xl border border-zinc-200 animate-in zoom-in-95 duration-200">
            <div className="w-12 h-12 bg-rose-50 text-rose-600 rounded-full flex items-center justify-center mb-6">
              <AlertTriangle className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-zinc-900">Delete Piece?</h3>
            <p className="text-sm text-zinc-500 mt-2 leading-relaxed">
              This action is permanent. The piece will be removed from your boutique archive and storefront.
            </p>
            <div className="flex gap-3 mt-8">
              <button 
                onClick={() => setDeleteConfirmationId(null)}
                className="flex-1 px-4 py-3 bg-zinc-100 hover:bg-zinc-200 text-zinc-900 rounded-xl text-sm font-bold transition-all"
              >
                Cancel
              </button>
              <button 
                onClick={handleDeleteProduct}
                className="flex-1 px-4 py-3 bg-rose-600 hover:bg-rose-700 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-rose-200"
              >
                Confirm Delete
              </button>
            </div>
          </div>
        </div>
      )}
      {/* Fast Action Loading Feedback */}
      {isSaving && (
        <FastActionLoader message={editingProduct ? 'Saving Piece Updates...' : 'Publishing New Piece to Live Storefront...'} />
      )}
    </div>
  );
};



